[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
attestation = "4v3eUeqjyyGq26qypp8jBEpTuHSYYP1tqB1H3DuwX4zc"

[programs.localnet]
attestation = "4v3eUeqjyyGq26qypp8jBEpTuHSYYP1tqB1H3DuwX4zc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node --test test/engine.test.mjs"
